### ISSUE TITLE
Make `browserless.token` a valid W3C Capability

### ISSUE THREAD

**Issue by christian-bromann** [browserless/docs#1]
In https://docs.browserless.io/docs/selenium-library.html you are stating that users should use: 

```js
chromeCapabilities.set('browserless.token', 'YOUR-API-TOKEN');
```

to authenticate with the service. However `browserless.token` is not a valid capability according to W3C WebDriver. Some frameworks like WebdriverIO fail on such protocol errors which is why I recommend to also allow setting the token via:

```js
chromeCapabilities.set('browserless:token', 'YOUR-API-TOKEN');
```

This way it would be totally valid according to the protocol. I hope you consider this kind of change. Thanks.

**Comment by osddeitf** [comment]
My pull request for fixing this has merged now that this issue could be closed.

**Comment by christian-bromann** [comment]
Awesome, thank you @osddeitf !

**Comment by christian-bromann** [comment]
@osddeitf I assume [the docs](https://docs.browserless.io/docs/selenium-library.html) will be also updated eventually?

**Comment by osddeitf** [comment]
I don't think so, it's upto the maintainer of Browserless. Apparently this repo is empty, and the other repo not having docs in it so that I could not create a PR to do so.
I'll ask the maintainer for this.
